version: "3.8"

services:
  api: &api
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      ASSETS_PATH: 'http://localhost:8080'
  app: &app
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
  prod:
    <<: *api
    environment:
      ASSETS_PATH: '/static/js'
    depends_on:
      - prod_assets
  prod_assets:
    <<: *app
    entrypoint: "./asset_build.sh"
