version: "3.8"

services:
  api: &api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      ASSETS_PATH: 'http://localhost:8080'
    entrypoint: "python main.py"
    depends_on:
      - app
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    entrypoint: ["/bin/sh", "-c", "yarn install && yarn start"]
  prod:
    <<: *api
    environment:
      ASSETS_PATH: '/static/js'
    depends_on:
      - prod_assets
  prod_assets:
    <<: *app
    entrypoint: ["/bin/sh", "-c", "yarn install && yarn build"]
