version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
  app:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
